name: Test

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to run'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
  pull_request:

jobs:
  plan:
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan') ||
      github.event_name == 'pull_request'
    runs-on:
    - ubuntu-latest

    steps:
    - name: Plan
      run: |
        echo 'Plan'
  apply:
    needs: plan
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    runs-on:
    - ubuntu-latest

    steps:
    - name: Apply
      run: |
        echo 'Apply'
