name: Test

on:
  workflow_dispatch:
  push:

jobs:
  plan:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.head_ref == 'master') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master')
    runs-on:
    - ubuntu

    steps:
    - name: Plan
      run: |
        echo 'Plan'
  apply:
    needs: plan
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on:
    - ubuntu
    environment: production

    steps:
    - name: Apply
      run: |
        echo 'Apply'
